### ISSUE TITLE
[Bug; PR created] Generate values window: Limited to 9 rows

### ISSUE THREAD

**Issue by htcfreek** [BdR76/RandomValuesNPP#7]
The feature "Generate random values" is limited to 9 rows because the for loops in https://github.com/BdR76/RandomValuesNPP/blob/a38b628b1af568dabb903368ec3f3ae76eb6522f/RandomValuesNppPlugin/Forms/GenerateForm.cs are using (1 .. <10) instead of (1 .. <=10).

**Comment by BdR76** [comment]
I've also increased the max columns to 30 instead of just 10. The code is a bit ugly, but that is due to how the Settings/SettingsBase was initially setup.

To anyone if you know how to add a List<string> as a setting AND integrate it nicely with the Settings/SettingsBase and the Settings dialog, feel free to submit a PR.
